service: voting

provider:
  name: google
  runtime: python3.12
  project: voting2024
  credentials: ~/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**

functions:
  scraper:
    handler: functions.scraper.get_kadencijos_xml
    events:
      - http: path
      
